name: Node.js CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["*"]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Compile Typst Files
              uses: siefkenj/compile-typst-action@latest
              with:
                  source_paths: "book/typst/book.typ book/typst/slides.typ"
                  output_paths: "book/typst/book.pdf book/typst/slides.pdf"
                  font_paths: "book/typst/fonts"

            # upload all the .wireit directories so that the test job can use them.
            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifacts
                  include-hidden-files: true
                  # Include package.json from the root so the file tree matches the full file tree of the repo
                  # (otherwise everything is normalized to the closest common ancestor folder)
                  path: |
                      ./book/**/*.pdf
